# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/**Tests.csproj'
- task: DockerCompose@0
  displayName: 'Build Docker Compose Services'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'hub.docker.com'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    includeLatestTag: true
- task: DockerCompose@0
  displayName: 'Push Images'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'hub.docker.com'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'