version: '3.4'

services:
  canteen:
    image: foodies/foody-canteen
    build:
      context: .
      dockerfile: Foodies.Foody.Canteen.Application/Dockerfile

  auth:
    image: foodies/foody-auth
    build:
      context: .
      dockerfile: Foodies.Foody.Auth.Application/Dockerfile
