version: '3.4'

services:
  auth:
    image: unidash/auth
    build:
      context: .
      dockerfile: Unidash.Auth.Application/Dockerfile
    depends_on:
      - mongodb

  canteen:
    image: unidash/canteen
    build:
      context: .
      dockerfile: Unidash.Canteen.Application/Dockerfile

  chat:
    image: unidash/chat
    build:
      context: .
      dockerfile: Unidash.Chat.Application/Dockerfile

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: