version: '3.4'

services:
  auth:
    networks: 
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        
        - "traefik.http.services.auth_api.loadbalancer.server.port=80"

        - "traefik.http.routers.auth_api-secured.rule=Host(`auth.dev.unidash.top`)"
        - "traefik.http.routers.auth_api-secured.entrypoints=web-secured"
        - "traefik.http.routers.auth_api-secured.tls.certresolver=defaultlts"


  canteen:
    networks: 
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        
        - "traefik.http.services.canteen_api.loadbalancer.server.port=80"

        - "traefik.http.routers.canteen_api-secured.rule=Host(`canteen.dev.unidash.top`)"
        - "traefik.http.routers.canteen_api-secured.entrypoints=web-secured"
        - "traefik.http.routers.canteen_api-secured.tls.certresolver=defaultlts"


  chat:
    networks: 
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        
        - "traefik.http.services.chat_api.loadbalancer.server.port=80"

        - "traefik.http.routers.chat_api-secured.rule=Host(`chat.dev.unidash.top`)"
        - "traefik.http.routers.chat_api-secured.entrypoints=web-secured"
        - "traefik.http.routers.chat_api-secured.tls.certresolver=defaultlts"


networks:
  proxy:
    external: true
