// <auto-generated />
using Unidash.Chat.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Unidash.Chat.Application.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Unidash.Chat.Application.Models.ChatChannel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Unidash.Chat.Application.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatChannelId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Unidash.Chat.Application.Models.ChatUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatChannelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Unidash.Chat.Application.Models.ChatMessage", b =>
                {
                    b.HasOne("Unidash.Chat.Application.Models.ChatChannel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatChannelId");
                });

            modelBuilder.Entity("Unidash.Chat.Application.Models.ChatUser", b =>
                {
                    b.HasOne("Unidash.Chat.Application.Models.ChatChannel", null)
                        .WithMany("Participants")
                        .HasForeignKey("ChatChannelId");
                });
#pragma warning restore 612, 618
        }
    }
}
